// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJmOvI9un0zgd0nOFjmZBAQaN30iyBg6s',
    appId: '1:313737940069:web:bd2876a4d2cbe9ac758a8c',
    messagingSenderId: '313737940069',
    projectId: 'walldecor-88cdf',
    authDomain: 'walldecor-88cdf.firebaseapp.com',
    storageBucket: 'walldecor-88cdf.firebasestorage.app',
    measurementId: 'G-KM1REFWKNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvguBjufM1Z8TeJB3vUNJEWGORHco16g4',
    appId: '1:313737940069:android:1c112c6561665e2c758a8c',
    messagingSenderId: '313737940069',
    projectId: 'walldecor-88cdf',
    storageBucket: 'walldecor-88cdf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyj6gyOcGR2bZPYdFPu3K7yDn2LK37Y1M',
    appId: '1:313737940069:ios:965ac6ad26c34ac9758a8c',
    messagingSenderId: '313737940069',
    projectId: 'walldecor-88cdf',
    storageBucket: 'walldecor-88cdf.firebasestorage.app',
    iosBundleId: 'com.example.walldecorapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyj6gyOcGR2bZPYdFPu3K7yDn2LK37Y1M',
    appId: '1:313737940069:ios:965ac6ad26c34ac9758a8c',
    messagingSenderId: '313737940069',
    projectId: 'walldecor-88cdf',
    storageBucket: 'walldecor-88cdf.firebasestorage.app',
    iosBundleId: 'com.example.walldecorapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJmOvI9un0zgd0nOFjmZBAQaN30iyBg6s',
    appId: '1:313737940069:web:7f1ef7d82a4299b8758a8c',
    messagingSenderId: '313737940069',
    projectId: 'walldecor-88cdf',
    authDomain: 'walldecor-88cdf.firebaseapp.com',
    storageBucket: 'walldecor-88cdf.firebasestorage.app',
    measurementId: 'G-2M7BT07P7L',
  );
}
